### ISSUE TITLE
Provide instructions for removal

### ISSUE THREAD

**Issue by arendej** [openshift/insights-operator#343]
Components not wanted should be able to be removed safely.

**Comment by tremes** [comment]
@funixz can you please elaborate what do you mean by components? I would welcome a slightly more thorough description. :)

**Comment by funixz** [comment]
In the markdown for the Metrics (Prometheus / Grafana) Operator there are instructions for removal of the operator and its components. For those of us that wish to test clusters without those components, it's helpful to be able to strip away things such as the Insights operator if feasible and not too damaging to the cluster in the short term
