### ISSUE TITLE
Pull Insights report retry mechanism is broken

### ISSUE THREAD

**Issue by joselsegura** [openshift/insights-operator#417]
When Insights Operator uploads a new archive, it waits for a configured amount of time and then starts to retrieve the report generated by the Insights Results Smart Proxy service.

If something goes wrong, it should be a retry mechanism that allow IO to try again after some time, but it doesn't work properly with some errors.

For example, if the Smart Proxy service returns a 404 (which is something very usual after the first archive upload), the retry mechanism doesn't try to get it again after some time. (The error is very likely to be in this code block: https://github.com/openshift/insights-operator/blob/7c60684c556da795663c602e618ae4bf7ed6621e/pkg/insights/insightsreport/insightsreport.go#L93).

This problem is impacting users, as they won't be able to see Insights results for their clusters in the OCP WebConsole until the second archive is uploaded

**Comment by tremes** [comment]
This issue can be closed, but it looks like I am not able to do that...... :-/

**Comment by joselsegura** [comment]
I cannot assign it to you, but it is already reviewed, resolved and merged, so I'll close it.

TYVM!
