### ISSUE TITLE
RFE: case attachment helper

### ISSUE THREAD

**Issue by raffaelespazzoli** [openshift/insights-operator#5]
consider adding a feature by which a cluster administrator can request the status of the cluster be attached to a case. The request could be triggered by a CR, which among other information contains the case id. the operator would then collect the must gather information, potentially SOS report on a subset of nodes etc... . Once the collection phase is done the operator would upload everything to the case as an attachment using a standard format (so potentially tools can be created on the support side to analyse the payload.

**Comment by alexandrevicenzi** [comment]
This does not sound like insights-operator job. You can request MG data or the insights archive from another system, it seems more of an integration with something else rather them the operator.

We do have ideas/proposals, or is somewhere in our roadmap to provide this information in cases.

Does this sound good to you @raffaelespazzoli?
