### ISSUE TITLE
RFE: Customized MachineConfigs Insights

### ISSUE THREAD

**Issue by LorbusChris** [openshift/insights-operator#52]
In preparation for the Ignition Spec V2 to V3 migration, we'd like to find out how many of our users have customized their MachineConfigs on their clusters.

Initial idea was to do something like this to find out whether or not a cluster has customized MCs (note the factor 2 to account for both worker and master MachineConfigPools and their respective rendered-MCs)

```
if [len(rendered-MCs) - 2*len(updates-count) > 2]
  customized = true
else
  customized = false
```

WDYT about this approach?

/cc @runcom @darkmuggle @ajeddeloh @smarterclayton

**Comment by runcom** [comment]
/cc @yuqi-zhang 

it wasn't clear from past conversations on topic _when_ are we going to ship such a thing (patch release before 4.3? 4.3 itself I doubt etc etc)

**Comment by smarterclayton** [comment]
This *could* be a metric on MCO.  If we could more accurately reflect it there, then we can capture the metric in insights only.

**Comment by yuqi-zhang** [comment]
> if [len(rendered-MCs) - 2*len(updates-count) > 2]
  customized = true
else
  customized = false

The general approach (idea of capturing updates) makes sense, although I don't know how robust a check like this would be, for example:
1. a user could have infra nodes, inflating the pool of rendered configs
2. a user could have applied a test custom MC and then deleted it, so we'd see an extra render although the cluster is still default.

Would be gray areas for that check. We could of course also consider those as customizations.

I also wonder if there is a good way to non-intrusively find out what customizations users apply. For example, what section (files, systemd units, etc) that people are applying.

**Comment by smarterclayton** [comment]
Yeah, anything that gets this closer to ground truth "has been customized, has not been customized" on a pool level (has 2 customized pools, 3 non-customized pools) is best.  Bonus points for types of customization (kubelet, units, other).  Everything else is gravy.

It is possible to do that calculation inside the operator.

Quick Q, does must gather already grab pools configs?

**Comment by runcom** [comment]
> Quick Q, does must gather already grab pools configs?

it does

**Comment by alexandrevicenzi** [comment]
It seems that we have enough information to move this request to Bugzilla, WDYT?
