### ISSUE TITLE
Support Operator Degraded

### ISSUE THREAD

**Issue by jdhirst1** [openshift/insights-operator#74]
Version: 4.4.0-0.okd-2020-02-04-174205

Using full pull secret including secret for cloud.redhat.com. 

The support operator becomes degraded as it attempts to post to cloud.redhat.com but is seeing the ingress certificate:
```
Unable to report: Post https://cloud.redhat.com/api/ingress/v1/upload: x509: certificate is valid for *.apps.okd.example.net, not cloud.redhat.com
```

**Comment by iNecas** [comment]
@mfojtik I don't have permissions to close issues in this repository, but we should do that per conversation https://github.com/openshift/okd/issues/71. Mind closing (and ideally adding more people from owners file to be able to manage this repo?)

**Comment by jdhirst1** [comment]
Closing issue.

**Comment by mfojtik** [comment]
@iNecas you can use /close

**Comment by baturorkun** [comment]
my base domain is  "company.com" and my cluster name is "okd" so I use  "api.okd.company.com"
and insight operator always degraded. is It a DNS issue?
